### PR TITLE
Use string representation of objects

### PR DESCRIPTION
**Pull request by fixe**

### CODE REVIEW

**Comment by scarney81** [comment]
So, I'm not sure what use case this is fulfilling. The data cannot be reconstituted from postgres in any way and would hit the fallback of an empty string (`''`).

**Comment by fixe** [comment]
If a boolean or a number are converted to their string representation why shouldn't objects be converted as well? Also, with the current implementation there is no way to understand if the developer was trying to set an actual empty string or an object.

**Comment by scarney81** [comment]
The `boolean` or `number` can be reconstituted from the database. It seems that storing `[object Object]` would simply be for debugging purposes because it cannot be turned back in to anything useful by a caller.

**Comment by fixe** [comment]
There is no way to reverse transform the saved value because the developer could be saving the string representation in the first place.

IMHO this PR helps the developer but feel free to close it.

**Comment by scarney81** [comment]
I think it's a valuable discussion. I'm just trying to make sure I fully understand the intent behind the pull request.

I edited in to my initial response in recognition of the fact that the developer could be overriding the `toString` impl - which actually I think makes potentially a good use case. My hesitation was in adding it only for debugging purposes - which perhaps a console.log message or something similar would be a bit more dev friendly than having to track it down in the database.

**Comment by scarney81** [comment]
This PR has been pub'd to `npm` as `2.3.1`

**Comment by fixe** [comment]
👍

**Pull request merged**
